# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler-worker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'scheduler-worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16scheduler-worker.proto\"h\n\x13ScheduleTaskRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x15\n\x05phase\x18\x02 \x01(\x0e\x32\x06.Phase\x12\x13\n\x0b\x62lock_table\x18\x03 \x03(\x05\x12\x11\n\ttoken_ids\x18\x04 \x03(\x05\";\n\x11ScheduleTaskBatch\x12&\n\x08requests\x18\x01 \x03(\x0b\x32\x14.ScheduleTaskRequest\"F\n\x0cSampledToken\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08token_id\x18\x02 \x01(\x05\x12\x10\n\x08\x66inished\x18\x03 \x01(\x08\"=\n\x14ScheduleTaskResponse\x12%\n\x0esampled_tokens\x18\x01 \x03(\x0b\x32\r.SampledToken*7\n\x05Phase\x12\x15\n\x11PHASE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PREFILL\x10\x01\x12\n\n\x06\x44\x45\x43ODE\x10\x02\x32L\n\x0fSchedulerWorker\x12\x39\n\x0cScheduleTask\x12\x12.ScheduleTaskBatch\x1a\x15.ScheduleTaskResponseB7Z5github.com/thouartmammal/llm_inference_server/gatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/thouartmammal/llm_inference_server/gateway'
  _globals['_PHASE']._serialized_start=328
  _globals['_PHASE']._serialized_end=383
  _globals['_SCHEDULETASKREQUEST']._serialized_start=26
  _globals['_SCHEDULETASKREQUEST']._serialized_end=130
  _globals['_SCHEDULETASKBATCH']._serialized_start=132
  _globals['_SCHEDULETASKBATCH']._serialized_end=191
  _globals['_SAMPLEDTOKEN']._serialized_start=193
  _globals['_SAMPLEDTOKEN']._serialized_end=263
  _globals['_SCHEDULETASKRESPONSE']._serialized_start=265
  _globals['_SCHEDULETASKRESPONSE']._serialized_end=326
  _globals['_SCHEDULERWORKER']._serialized_start=385
  _globals['_SCHEDULERWORKER']._serialized_end=461
# @@protoc_insertion_point(module_scope)
