// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: scheduler-worker.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PREFILL           Phase = 1
	Phase_DECODE            Phase = 2
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PREFILL",
		2: "DECODE",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PREFILL":           1,
		"DECODE":            2,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_worker_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_scheduler_worker_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{0}
}

type ScheduleTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Phase         Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=Phase" json:"phase,omitempty"`
	BlockTable    []int32                `protobuf:"varint,3,rep,packed,name=block_table,json=blockTable,proto3" json:"block_table,omitempty"`
	TokenIds      []int32                `protobuf:"varint,4,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskRequest) Reset() {
	*x = ScheduleTaskRequest{}
	mi := &file_scheduler_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskRequest) ProtoMessage() {}

func (x *ScheduleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleTaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScheduleTaskRequest) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *ScheduleTaskRequest) GetBlockTable() []int32 {
	if x != nil {
		return x.BlockTable
	}
	return nil
}

func (x *ScheduleTaskRequest) GetTokenIds() []int32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type ScheduleTaskBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ScheduleTaskRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskBatch) Reset() {
	*x = ScheduleTaskBatch{}
	mi := &file_scheduler_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskBatch) ProtoMessage() {}

func (x *ScheduleTaskBatch) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskBatch.ProtoReflect.Descriptor instead.
func (*ScheduleTaskBatch) Descriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleTaskBatch) GetRequests() []*ScheduleTaskRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type SampledToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenId       int32                  `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampledToken) Reset() {
	*x = SampledToken{}
	mi := &file_scheduler_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampledToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampledToken) ProtoMessage() {}

func (x *SampledToken) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampledToken.ProtoReflect.Descriptor instead.
func (*SampledToken) Descriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{2}
}

func (x *SampledToken) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SampledToken) GetTokenId() int32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *SampledToken) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type ScheduleTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampledTokens []*SampledToken        `protobuf:"bytes,1,rep,name=sampled_tokens,json=sampledTokens,proto3" json:"sampled_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskResponse) Reset() {
	*x = ScheduleTaskResponse{}
	mi := &file_scheduler_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskResponse) ProtoMessage() {}

func (x *ScheduleTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTaskResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleTaskResponse) GetSampledTokens() []*SampledToken {
	if x != nil {
		return x.SampledTokens
	}
	return nil
}

type CancelGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGenerationRequest) Reset() {
	*x = CancelGenerationRequest{}
	mi := &file_scheduler_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGenerationRequest) ProtoMessage() {}

func (x *CancelGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGenerationRequest.ProtoReflect.Descriptor instead.
func (*CancelGenerationRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{4}
}

func (x *CancelGenerationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CancelGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheReleased bool                   `protobuf:"varint,1,opt,name=cache_released,json=cacheReleased,proto3" json:"cache_released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGenerationResponse) Reset() {
	*x = CancelGenerationResponse{}
	mi := &file_scheduler_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGenerationResponse) ProtoMessage() {}

func (x *CancelGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGenerationResponse.ProtoReflect.Descriptor instead.
func (*CancelGenerationResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_worker_proto_rawDescGZIP(), []int{5}
}

func (x *CancelGenerationResponse) GetCacheReleased() bool {
	if x != nil {
		return x.CacheReleased
	}
	return false
}

var File_scheduler_worker_proto protoreflect.FileDescriptor

const file_scheduler_worker_proto_rawDesc = "" +
	"\n" +
	"\x16scheduler-worker.proto\"\x90\x01\n" +
	"\x13ScheduleTaskRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x06.PhaseR\x05phase\x12\x1f\n" +
	"\vblock_table\x18\x03 \x03(\x05R\n" +
	"blockTable\x12\x1b\n" +
	"\ttoken_ids\x18\x04 \x03(\x05R\btokenIds\"E\n" +
	"\x11ScheduleTaskBatch\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.ScheduleTaskRequestR\brequests\"d\n" +
	"\fSampledToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x05R\atokenId\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\"L\n" +
	"\x14ScheduleTaskResponse\x124\n" +
	"\x0esampled_tokens\x18\x01 \x03(\v2\r.SampledTokenR\rsampledTokens\"8\n" +
	"\x17CancelGenerationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"A\n" +
	"\x18CancelGenerationResponse\x12%\n" +
	"\x0ecache_released\x18\x01 \x01(\bR\rcacheReleased*7\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPREFILL\x10\x01\x12\n" +
	"\n" +
	"\x06DECODE\x10\x022\x95\x01\n" +
	"\x0fSchedulerWorker\x129\n" +
	"\fScheduleTask\x12\x12.ScheduleTaskBatch\x1a\x15.ScheduleTaskResponse\x12G\n" +
	"\x10CancelGeneration\x12\x18.CancelGenerationRequest\x1a\x19.CancelGenerationResponseB7Z5github.com/thouartmammal/llm_inference_server/gatewayb\x06proto3"

var (
	file_scheduler_worker_proto_rawDescOnce sync.Once
	file_scheduler_worker_proto_rawDescData []byte
)

func file_scheduler_worker_proto_rawDescGZIP() []byte {
	file_scheduler_worker_proto_rawDescOnce.Do(func() {
		file_scheduler_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_worker_proto_rawDesc), len(file_scheduler_worker_proto_rawDesc)))
	})
	return file_scheduler_worker_proto_rawDescData
}

var file_scheduler_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scheduler_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scheduler_worker_proto_goTypes = []any{
	(Phase)(0),                       // 0: Phase
	(*ScheduleTaskRequest)(nil),      // 1: ScheduleTaskRequest
	(*ScheduleTaskBatch)(nil),        // 2: ScheduleTaskBatch
	(*SampledToken)(nil),             // 3: SampledToken
	(*ScheduleTaskResponse)(nil),     // 4: ScheduleTaskResponse
	(*CancelGenerationRequest)(nil),  // 5: CancelGenerationRequest
	(*CancelGenerationResponse)(nil), // 6: CancelGenerationResponse
}
var file_scheduler_worker_proto_depIdxs = []int32{
	0, // 0: ScheduleTaskRequest.phase:type_name -> Phase
	1, // 1: ScheduleTaskBatch.requests:type_name -> ScheduleTaskRequest
	3, // 2: ScheduleTaskResponse.sampled_tokens:type_name -> SampledToken
	2, // 3: SchedulerWorker.ScheduleTask:input_type -> ScheduleTaskBatch
	5, // 4: SchedulerWorker.CancelGeneration:input_type -> CancelGenerationRequest
	4, // 5: SchedulerWorker.ScheduleTask:output_type -> ScheduleTaskResponse
	6, // 6: SchedulerWorker.CancelGeneration:output_type -> CancelGenerationResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scheduler_worker_proto_init() }
func file_scheduler_worker_proto_init() {
	if File_scheduler_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_worker_proto_rawDesc), len(file_scheduler_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_worker_proto_goTypes,
		DependencyIndexes: file_scheduler_worker_proto_depIdxs,
		EnumInfos:         file_scheduler_worker_proto_enumTypes,
		MessageInfos:      file_scheduler_worker_proto_msgTypes,
	}.Build()
	File_scheduler_worker_proto = out.File
	file_scheduler_worker_proto_goTypes = nil
	file_scheduler_worker_proto_depIdxs = nil
}
