// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: scheduler-worker.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerWorker_ScheduleTask_FullMethodName     = "/SchedulerWorker/ScheduleTask"
	SchedulerWorker_CancelGeneration_FullMethodName = "/SchedulerWorker/CancelGeneration"
)

// SchedulerWorkerClient is the client API for SchedulerWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerWorkerClient interface {
	ScheduleTask(ctx context.Context, in *ScheduleTaskBatch, opts ...grpc.CallOption) (*ScheduleTaskResponse, error)
	CancelGeneration(ctx context.Context, in *CancelGenerationRequest, opts ...grpc.CallOption) (*CancelGenerationResponse, error)
}

type schedulerWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerWorkerClient(cc grpc.ClientConnInterface) SchedulerWorkerClient {
	return &schedulerWorkerClient{cc}
}

func (c *schedulerWorkerClient) ScheduleTask(ctx context.Context, in *ScheduleTaskBatch, opts ...grpc.CallOption) (*ScheduleTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTaskResponse)
	err := c.cc.Invoke(ctx, SchedulerWorker_ScheduleTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerWorkerClient) CancelGeneration(ctx context.Context, in *CancelGenerationRequest, opts ...grpc.CallOption) (*CancelGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelGenerationResponse)
	err := c.cc.Invoke(ctx, SchedulerWorker_CancelGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerWorkerServer is the server API for SchedulerWorker service.
// All implementations must embed UnimplementedSchedulerWorkerServer
// for forward compatibility.
type SchedulerWorkerServer interface {
	ScheduleTask(context.Context, *ScheduleTaskBatch) (*ScheduleTaskResponse, error)
	CancelGeneration(context.Context, *CancelGenerationRequest) (*CancelGenerationResponse, error)
	mustEmbedUnimplementedSchedulerWorkerServer()
}

// UnimplementedSchedulerWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerWorkerServer struct{}

func (UnimplementedSchedulerWorkerServer) ScheduleTask(context.Context, *ScheduleTaskBatch) (*ScheduleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleTask not implemented")
}
func (UnimplementedSchedulerWorkerServer) CancelGeneration(context.Context, *CancelGenerationRequest) (*CancelGenerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelGeneration not implemented")
}
func (UnimplementedSchedulerWorkerServer) mustEmbedUnimplementedSchedulerWorkerServer() {}
func (UnimplementedSchedulerWorkerServer) testEmbeddedByValue()                         {}

// UnsafeSchedulerWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerWorkerServer will
// result in compilation errors.
type UnsafeSchedulerWorkerServer interface {
	mustEmbedUnimplementedSchedulerWorkerServer()
}

func RegisterSchedulerWorkerServer(s grpc.ServiceRegistrar, srv SchedulerWorkerServer) {
	// If the following call pancis, it indicates UnimplementedSchedulerWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerWorker_ServiceDesc, srv)
}

func _SchedulerWorker_ScheduleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTaskBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerWorkerServer).ScheduleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerWorker_ScheduleTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerWorkerServer).ScheduleTask(ctx, req.(*ScheduleTaskBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerWorker_CancelGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerWorkerServer).CancelGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerWorker_CancelGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerWorkerServer).CancelGeneration(ctx, req.(*CancelGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerWorker_ServiceDesc is the grpc.ServiceDesc for SchedulerWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SchedulerWorker",
	HandlerType: (*SchedulerWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleTask",
			Handler:    _SchedulerWorker_ScheduleTask_Handler,
		},
		{
			MethodName: "CancelGeneration",
			Handler:    _SchedulerWorker_CancelGeneration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler-worker.proto",
}
